const data = {
    products: [{
            name: 'Tecno POP',
            slug: 'tecno-pop',
            category: 'Phones',
            image: '/images/p2.JPG',
            price: 140,
            countInStock: 15,
            brand: 'Tecno',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality phone',
        },
        {
            name: 'Apple IPhone 13 Pro',
            slug: 'apple-iphone-13-pro',
            category: 'Phone',
            image: '/images/p1.jpg',
            price: 450,
            countInStock: 20,
            brand: 'Apple',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality phone',
        },
        {
            name: 'Techno Sonic Earpod',
            slug: 'techno-sonic-earpod',
            category: 'Earpod',
            image: '/images/p3.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Tecno',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality earpod',
        },
        {
            name: 'Apple Earpod',
            slug: 'apple-earpod',
            category: 'Earpod',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality earpod',
        },
    ],
}
export default data